<?php
namespace Mathielen\ImportEngine\Storage\Type\Factory;

class CsvAutoDelimiterTypeFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @dataProvider getGuessDelimiterData
     */
    public function testGuessDelimiter($line, $expectedDelimiter)
    {
        $csvAutoDelimiterTypeFactory = new CsvAutoDelimiterTypeFactory();
        $actualDelimiter = $csvAutoDelimiterTypeFactory->guessDelimiter($line);

        $this->assertEquals($expectedDelimiter, $actualDelimiter);
    }

    public function getGuessDelimiterData()
    {
        return array(
            array('Anrede;Name;StrasseHausnr;Plz', ';'),
            array('SATZART#BESTELLER-ID#MARKE#BEST-LAENDER-KZ#BEST-MARKE-KZ#BEST-DEALER#AUSL-LAENDER-KZ#AUSL-MARKE-KZ#AUSL-DEALER#VERM-LAENDER-KZ#VERM-MARKE-KZ#VERM-DEALER#BETR-LAENDER-KZ#BETR-MARKE-KZ#BETR-DEALER#KOMMISSIONS-JAHR#KOMMISSIONS-NUMMER#ZBHF-LAENDER-KZ#ZBHF-BAHNHOF#ZBHF-TYP#SONDERABNEHMER#ERSTELL-DATUM#FZG-ID-NUMMER#MODELLGRUPPE#MODELL-JAHR#LVP#MODELL#FARBE#PR-NR(1)#PR-NR(2)#PR-NR(3)#PR-NR(4)#PR-NR(5)#PR-NR(6)#PR-NR(7)#PR-NR(8)#PR-NR(9)#PR-NR(10)#PR-NR(11)#PR-NR(12)#PR-NR(13)#PR-NR(14)#PR-NR(15)#PR-NR(16)#PR-NR(17)#PR-NR(18)#PR-NR(19)#PR-NR(20)#PR-NR(21)#PR-NR(22)#PR-NR(23)#PR-NR(24)#PR-NR(25)#PR-NR(26)#PR-NR(27)#PR-NR(28)#PR-NR(29)#PR-NR(30)#PR-NR(31)#PR-NR(32)#PR-NR(33)#PR-NR(34)#PR-NR(35)#PR-NR(36)#PR-NR(37)#PR-NR(38)#PR-NR(39)#PR-NR(40)#PR-NR(41)#PR-NR(42)#PR-NR(43)#PR-NR(44)#PR-NR(45)#PR-NR(46)#PR-NR(47)#PR-NR(48)#PR-NR(49)#PR-NR(50)#PR-NR(51)#PR-NR(52)#PR-NR(53)#PR-NR(54)#PR-NR(55)#PR-NR(56)#PR-NR(57)#PR-NR(58)#PR-NR(59)#PR-NR(60)#VERKAUFSPREIS#AE-DATUM#KZ-DATUM#AL-DATUM#KUNDEN-NUMMER#GROSS-KD-NUMMER#AUFTRAGSART#KUNDENGRUPPE#ARTIFICIAL-PERSON#ANREDE#TITEL#TEXTANREDE#NAMENSZUSATZ#NACHNAME#VORNAME-1#VORNAME-2#FIRMENNAME#BRANCHE#FIRMENZUSATZ#ABTEILUNG#STRASSE-1#STRASSE-2#STRASSE-3#HAUSNUMMER#COUNTRY-CODE#POSTLEITZAHL#ORT#POSTFACH#ADRESSCHECK#KAUEFERART#FINANZIERT#KUNDENCLUB#MEMBERSHIP#CC-CLUBKARTEN#TELEFON-FEST-BERUFLICH#TELEFON-MOBIL-BERUFLICH#FAX-BERUFLICH#EMAIL-BERUFLICH#TELEFON-FEST-PRIVAT#TELEFON-MOBIL-PRIVAT#FAX-PRIVAT#EMAIL-PRIVAT#TELEFON-FEST-TEMPORAER#TELEFON-MOBIL-TEMPORAER#FAX-TEMPORAER#EMAIL-TEMPORAER#GEBURTSJAHR#KUDATEN-KZ#KUNDENSPRACHE#INFOS#VERKAEUFER#LIEFERSTATUS#VORGANGSSTATUS#ERFASSUNGSSTATUS#AENDERUNGSSTATUS#SPERRSTATUS#FEHLERSTATUS#VFM-01#VFM-02#VFM-03#EROBERUNG#VERSANDART#VB-BEZIRK-NR#KV-DATUM#AB-DATUM#EF-DATUM#RECHNUNGS-DATUM#RECHNUNGS-NUMMER#RECHNUNGS-BETRAG#MWST-BETRAG#FAHRZEUG-PREIS#SONDERKOSTEN-BETRAG#TRANSPORT-KOSTEN#VERSICHERUNGS-KOSTEN#GEBUEHREN#AUSWAHL-KZ#ANSCHLUSSGARANTIE#ANSCHLUSSGARANTIE-UST#LEASING-GESELLSCHAFT#GK-KUNDEN-KONTO-FSAG#EXTERNE-KUNDEN-KZ#EXTERNE-KUNDEN-NR#GK-VERTRAGS-ART#HAENDLER-KOMMISSION#WERKSKENNZEICHEN#PRODUKTIONSWOCHE#AUSGLEICHKENNZEICHEN#PREISBEWERTUNGSDATUM#LETZTES-ÄNDERUNGSDATUM#ZUGESAGTER-LIEFERTERMIN#DE-VOLLSTÄNDIG#DE-POSTALISCH#DE-TELEFON-SMS#DE-EMAIL#DE-KEIN-KONTAKT#DE-TBD#RESERVIERT', '#'),
            array('Mr.;"Abdiel Johnson";"106 Aryanna Hollow Suite 141";27618;"Port Roslyn";1-677-290-6068x33959;harry84@hodkiewicz.info', ';'),
            array("Anrede\tName\tStrasseHausnr\tPlz", "\t"),
            array('Miss;"Antonina Bernhard";"845 Cormier Forest Suite 067";02350;"Port Vanessashire";1-644-400-5246x86657;schaefer.teagan@hotmail.com', ';')
        );
    }

}
